### ISSUE TITLE
上传显示证书错误

### ISSUE THREAD

**Issue by Playfullycat** [hellodk34/picgo-plugin-lankong#16]
[https://jpgbed.com/i/2022/10/24/635688f9d5cd5.png](url)

选不选Ignore certificate error都试过 
域名[https://jpgbed.com](url)
用postman可以没有问题

**Comment by hellodk34** [comment]
@Playfullycat 看能否贴一下 picgo 的日志

**Comment by Playfullycat** [comment]
@hellodk34 
2022-10-24 20:38:04 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: tunneling socket could not be established, cause=socket hang up
    at new RequestError (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at ClientRequest.onError (E:\Software\PicGo\resources\app.asar\node_modules\tunnel-agent\index.js:179:21)
    at Object.onceWrapper (events.js:288:20)
    at ClientRequest.emit (events.js:200:13)
-------Error Stack End------- 
2022-10-24 20:38:17 [PicGo INFO] Before transform 
2022-10-24 20:38:17 [PicGo INFO] Transforming... Current transformer is [path] 
2022-10-24 20:38:17 [PicGo INFO] Before upload 
2022-10-24 20:38:17 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-10-24 20:38:17 [PicGo INFO] Uploading... Current uploader is [lankong] 
2022-10-24 20:38:17 [PicGo WARN] failed 
2022-10-24 20:38:17 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at Socket.socketErrorListener (_http_client.js:402:9)
    at Socket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2022-10-24 20:38:17 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: read ECONNRESET
    at new RequestError (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at Socket.socketErrorListener (_http_client.js:402:9)
    at Socket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2022-10-24 20:39:32 [PicGo INFO] Before transform 
2022-10-24 20:39:32 [PicGo INFO] Transforming... Current transformer is [path] 
2022-10-24 20:39:32 [PicGo INFO] Before upload 
2022-10-24 20:39:32 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-10-24 20:39:32 [PicGo INFO] Uploading... Current uploader is [lankong] 
2022-10-24 20:39:32 [PicGo WARN] failed 
2022-10-24 20:39:32 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: certificate has expired
    at new RequestError (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2022-10-24 20:39:32 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: certificate has expired
    at new RequestError (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2022-10-24 20:39:42 [PicGo INFO] Before transform 
2022-10-24 20:39:42 [PicGo INFO] Transforming... Current transformer is [path] 
2022-10-24 20:39:42 [PicGo INFO] Before upload 
2022-10-24 20:39:42 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-10-24 20:39:42 [PicGo INFO] Uploading... Current uploader is [lankong] 
2022-10-24 20:39:43 [PicGo WARN] failed 
2022-10-24 20:39:43 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: certificate has expired
    at new RequestError (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2022-10-24 20:39:43 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: certificate has expired
    at new RequestError (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2022-10-24 20:42:27 [PicGo INFO] Before transform 
2022-10-24 20:42:27 [PicGo INFO] Transforming... Current transformer is [path] 
2022-10-24 20:42:27 [PicGo INFO] Before upload 
2022-10-24 20:42:27 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-10-24 20:42:27 [PicGo INFO] Uploading... Current uploader is [lankong] 
2022-10-24 20:42:28 [PicGo WARN] failed 
2022-10-24 20:42:28 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: certificate has expired
    at new RequestError (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2022-10-24 20:42:28 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: certificate has expired
    at new RequestError (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2022-10-26 08:36:59 [PicGo INFO] [PicGo Server] is listening at 36677 
2022-10-26 08:37:07 [PicGo INFO] Before transform 
2022-10-26 08:37:07 [PicGo INFO] Transforming... Current transformer is [path] 
2022-10-26 08:37:07 [PicGo INFO] Before upload 
2022-10-26 08:37:07 [PicGo INFO] beforeUploadPlugins: renameFn running 
2022-10-26 08:37:07 [PicGo INFO] Uploading... Current uploader is [lankong] 
2022-10-26 08:37:07 [PicGo WARN] failed 
2022-10-26 08:37:07 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: certificate has expired
    at new RequestError (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End------- 
2022-10-26 08:37:07 [PicGo ERROR] 
------Error Stack Begin------
RequestError: Error: certificate has expired
    at new RequestError (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\errors.js:14:15)
    at Request.plumbing.callback (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:87:29)
    at Request.RP$callback [as _callback] (E:\Software\PicGo\resources\app.asar\node_modules\request-promise-core\lib\plumbing.js:46:31)
    at self.callback (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:185:22)
    at Request.emit (events.js:200:13)
    at Request.onRequestError (E:\Software\PicGo\resources\app.asar\node_modules\request\request.js:877:8)
    at ClientRequest.emit (events.js:200:13)
    at TLSSocket.socketErrorListener (_http_client.js:402:9)
    at TLSSocket.emit (events.js:200:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
-------Error Stack End-------

**Comment by hellodk34** [comment]
不好意思才看到。

> RequestError: Error: certificate has expired

看上去和之前我遇到的错误一样，但是我打开 **Ignore certificate error** 开关就能成功上传。我访问了你提供的图片直链，看了下证书也是 Let's Encrypt 提供的三个月的泛域名证书，按理说应该没问题的。暂时不明白是什么造成的。后续可以的话，你能注册一个账号（在你的图床平台上），我调试一下看看吗？

**Comment by Playfullycat** [comment]
@hellodk34 谢谢作者回复 我把Permission 改成public后就可以上传了

**Comment by hellodk34** [comment]
@Playfullycat 那就好，恭喜 👏🏻
