### ISSUE TITLE
修改路径命名规则后无法使用picgo上传

### ISSUE THREAD

**Issue by nanbowan323** [hellodk34/picgo-plugin-lankong#20]
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/20452341/210298597-b7fb7da1-d692-484d-b112-c15cf14205ed.png">
修改路径后上传会提示报错日志如下（未修改前上传正常）。请问该如何解决
![image](https://user-images.githubusercontent.com/20452341/210299879-862c4e21-4f02-4f7b-a586-cfcec60009df.png)

**Comment by nanbowan323** [comment]
TypeError: Cannot read properties of undefined (reading 'name')
    at FormData._getContentDisposition (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/form-data/lib/form_data.js:227:40)
    at FormData._multiPartHeader (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/form-data/lib/form_data.js:178:33)
    at FormData.append (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/form-data/lib/form_data.js:71:21)
    at mt (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:47526)
    at /Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:49862
    at Ut.request (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:50075)
    at Object.handle (/Users/nanbowan/Library/Application Support/picgo/node_modules/picgo-plugin-lankong/dist/index.js:180:42)
    at $e.doUpload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:17221)
    at $e.start (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:15980)
    at async Tt.upload (/Applications/PicGo.app/Contents/Resources/app.asar/node_modules/picgo/dist/index.cjs.js:1:71270)
-------Error Stack End-------

**Comment by hellodk34** [comment]
没有测试过这个功能，请问为何关闭了 issue？  @nanbowan323

**Comment by nanbowan323** [comment]
因为过了两天自动好了😂
