### ISSUE TITLE
值未定义错误

### ISSUE THREAD

**Issue by qianxiao996** [hellodk34/picgo-plugin-lankong#29]
2023-08-20 14:13:11 [PicGo INFO] upload clipboard file 
2023-08-20 14:13:11 [PicGo INFO] Before transform 
2023-08-20 14:13:11 [PicGo INFO] Transforming... Current transformer is [path] 
2023-08-20 14:13:11 [PicGo INFO] Before upload 
2023-08-20 14:13:11 [PicGo INFO] Uploading... Current uploader is [lankong] 
2023-08-20 14:13:11 [PicGo WARN] failed 
2023-08-20 14:13:11 [PicGo ERROR] 
------Error Stack Begin------
TypeError: Cannot read properties of undefined (reading 'value')
    at postOptions (C:\Users\qianxiao996\AppData\Roaming\picgo\node_modules\picgo-plugin-lankong\dist\index.js:119:48)
    at Object.handle (C:\Users\qianxiao996\AppData\Roaming\picgo\node_modules\picgo-plugin-lankong\dist\index.js:179:32)
    at je.doUpload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:19814)
    at je.start (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18573)
    at async $t.upload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:73078)
    at async Object.upload (D:\PicGo\resources\app.asar\index.js:2:690303)
    at async D:\PicGo\resources\app.asar\index.js:2:692247
    at async ur (D:\PicGo\resources\app.asar\index.js:2:692079)
-------Error Stack End------- 
2023-08-20 14:13:11 [PicGo ERROR] 
------Error Stack Begin------
TypeError: Cannot read properties of undefined (reading 'value')
    at postOptions (C:\Users\qianxiao996\AppData\Roaming\picgo\node_modules\picgo-plugin-lankong\dist\index.js:119:48)
    at Object.handle (C:\Users\qianxiao996\AppData\Roaming\picgo\node_modules\picgo-plugin-lankong\dist\index.js:179:32)
    at je.doUpload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:19814)
    at je.start (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:18573)
    at async $t.upload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:73078)
    at async Object.upload (D:\PicGo\resources\app.asar\index.js:2:690303)
    at async D:\PicGo\resources\app.asar\index.js:2:692247
    at async ur (D:\PicGo\resources\app.asar\index.js:2:692079)
-------Error Stack End-------

**Comment by hellodk34** [comment]
重设插件值再重启 picgo
