### ISSUE TITLE
兰空v1

### ISSUE THREAD

**Issue by heiyuan0801** [hellodk34/picgo-plugin-lankong#35]
兰空v1 企业版 上传报错 

2024-01-21 16:04:22 [PicGo ERROR] 
------Error Stack Begin------
Error
    at Object.handle (C:\Users\ASUS\AppData\Roaming\picgo\node_modules\picgo-plugin-lankong\dist\index.js:197:23)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (C:\Users\ASUS\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17198)
    at async $e.start (C:\Users\ASUS\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15969)
    at async Tt.upload (C:\Users\ASUS\AppData\Local\Programs\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:71270)
    at async Object.upload (C:\Users\ASUS\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:653584)
    at async jn (C:\Users\ASUS\AppData\Local\Programs\PicGo\resources\app.asar\background.js:2:656251)
-------Error Stack End-------

**Comment by hellodk34** [comment]
没有兰空企业版……

本插件没有考虑适配企业版，和对应开源协议违背。
